//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: login.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// The greeting service definition.
///
/// Usage: instantiate `Login_LoginClient`, then call methods of this protocol to make API calls.
public protocol Login_LoginClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Login_LoginClientInterceptorFactoryProtocol? { get }

  func login(
    _ request: Login_LoginRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Login_LoginRequest, Login_LoginResponse>
}

extension Login_LoginClientProtocol {
  public var serviceName: String {
    return "login.Login"
  }

  /// Sends a greeting.
  ///
  /// - Parameters:
  ///   - request: Request to send to Login.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func login(
    _ request: Login_LoginRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Login_LoginRequest, Login_LoginResponse> {
    return self.makeUnaryCall(
      path: "/login.Login/Login",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLoginInterceptors() ?? []
    )
  }
}

public protocol Login_LoginClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'login'.
  func makeLoginInterceptors() -> [ClientInterceptor<Login_LoginRequest, Login_LoginResponse>]
}

public final class Login_LoginClient: Login_LoginClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Login_LoginClientInterceptorFactoryProtocol?

  /// Creates a client for the login.Login service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Login_LoginClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// The greeting service definition.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Login_LoginProvider: CallHandlerProvider {
  var interceptors: Login_LoginServerInterceptorFactoryProtocol? { get }

  /// Sends a greeting.
  func login(request: Login_LoginRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Login_LoginResponse>
}

extension Login_LoginProvider {
  public var serviceName: Substring { return "login.Login" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Login":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Login_LoginRequest>(),
        responseSerializer: ProtobufSerializer<Login_LoginResponse>(),
        interceptors: self.interceptors?.makeLoginInterceptors() ?? [],
        userFunction: self.login(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Login_LoginServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'login'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeLoginInterceptors() -> [ServerInterceptor<Login_LoginRequest, Login_LoginResponse>]
}
